# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Write Data from DHT11 Sensor into Shared Memory 
#' 
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
DHT11_writeMemory <- function(timeDelay = 1000L, pin = 0L) {
    invisible(.Call(`_RaspberryPiR_DHT11_writeMemory`, timeDelay, pin))
}

DHT11_readMemory <- function(n = 1L) {
    .Call(`_RaspberryPiR_DHT11_readMemory`, n)
}

DHT11_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_DHT11_freeMemory`))
}

DHT11_scanPointer <- function() {
    .Call(`_RaspberryPiR_DHT11_scanPointer`)
}

PhotoRes_writeMemory <- function(timeDelay = 1000L, pin = 7L) {
    invisible(.Call(`_RaspberryPiR_PhotoRes_writeMemory`, timeDelay, pin))
}

PhotoRes_readMemory <- function(n = 5L) {
    .Call(`_RaspberryPiR_PhotoRes_readMemory`, n)
}

PhotoRes_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_PhotoRes_freeMemory`))
}

PhotoRes_scanPointer <- function() {
    .Call(`_RaspberryPiR_PhotoRes_scanPointer`)
}

MQ2_writeMemory <- function(timeDelay = 1000L, SPICLK = 14L, SPIMISO = 13L, SPIMOSI = 12L, SPICS = 10L, mq2_dpin = 25L, mq2_apin = 0L) {
    invisible(.Call(`_RaspberryPiR_MQ2_writeMemory`, timeDelay, SPICLK, SPIMISO, SPIMOSI, SPICS, mq2_dpin, mq2_apin))
}

MQ2_readMemory <- function(n = 1L) {
    .Call(`_RaspberryPiR_MQ2_readMemory`, n)
}

MQ2_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_MQ2_freeMemory`))
}

MQ2_scanPointer <- function() {
    .Call(`_RaspberryPiR_MQ2_scanPointer`)
}

RPiCam_writeMemory <- function(timeDelay = 1000L) {
    invisible(.Call(`_RaspberryPiR_RPiCam_writeMemory`, timeDelay))
}

RPiCam_readMemory <- function(n = 5L) {
    .Call(`_RaspberryPiR_RPiCam_readMemory`, n)
}

RPiCam_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_RPiCam_freeMemory`))
}

RPiCam_scanPointer <- function() {
    .Call(`_RaspberryPiR_RPiCam_scanPointer`)
}

testing_writeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_testing_writeMemory`))
}

testing_readMemory <- function(x = 5L) {
    .Call(`_RaspberryPiR_testing_readMemory`, x)
}

testing_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_testing_freeMemory`))
}

testingDHT <- function(pin = 0L) {
    .Call(`_RaspberryPiR_testingDHT`, pin)
}

testingPhotoRes <- function(pin = 7L) {
    .Call(`_RaspberryPiR_testingPhotoRes`, pin)
}

testingMQ2 <- function(pin = 0L, SPICLK = 14L, SPIMISO = 13L, SPIMOSI = 12L, SPICS = 10L, mq2_dpin = 25L, mq2_apin = 0L) {
    .Call(`_RaspberryPiR_testingMQ2`, pin, SPICLK, SPIMISO, SPIMOSI, SPICS, mq2_dpin, mq2_apin)
}

simpleCapture <- function(path = "/home/pi/Pictures/raspicam_image.ppm", width = 1L, height = 1L) {
    .Call(`_RaspberryPiR_simpleCapture`, path, width, height)
}

LL_wiringPiSetup <- function() {
    invisible(.Call(`_RaspberryPiR_LL_wiringPiSetup`))
}

LL_pinMode <- function(pin, mode) {
    invisible(.Call(`_RaspberryPiR_LL_pinMode`, pin, mode))
}

LL_digitalWrite <- function(pin, mode) {
    invisible(.Call(`_RaspberryPiR_LL_digitalWrite`, pin, mode))
}

LL_digitalRead <- function(pin) {
    .Call(`_RaspberryPiR_LL_digitalRead`, pin)
}

LL_pullUpDnControl <- function(pin, pud) {
    invisible(.Call(`_RaspberryPiR_LL_pullUpDnControl`, pin, pud))
}

LL_millis <- function() {
    .Call(`_RaspberryPiR_LL_millis`)
}

LL_micros <- function() {
    .Call(`_RaspberryPiR_LL_micros`)
}

