# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

exec <- function(cmd) {
    .Call(`_RaspberryPiR_exec`, cmd)
}

fibonacci_main <- function(x) {
    .Call(`_RaspberryPiR_fibonacci_main`, x)
}

rcpp_hello_world <- function() {
    .Call(`_RaspberryPiR_rcpp_hello_world`)
}

