# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DHT11_writeMemory <- function(pin = 0L, length = 100L, timeDelay = 1000L) {
    invisible(.Call(`_RaspberryPiR_DHT11_writeMemory`, pin, length, timeDelay))
}

DHT11_readMemory <- function(n = 1L) {
    .Call(`_RaspberryPiR_DHT11_readMemory`, n)
}

DHT11_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_DHT11_freeMemory`))
}

PhotoRes_writeMemory <- function(pin = 7L, length = 100L, timeDelay = 1000L) {
    invisible(.Call(`_RaspberryPiR_PhotoRes_writeMemory`, pin, length, timeDelay))
}

PhotoRes_readMemory <- function(n = 1L) {
    .Call(`_RaspberryPiR_PhotoRes_readMemory`, n)
}

PhotoRes_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_PhotoRes_freeMemory`))
}

testing_writeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_testing_writeMemory`))
}

testing_readMemory <- function(x = 5L) {
    .Call(`_RaspberryPiR_testing_readMemory`, x)
}

testing_freeMemory <- function() {
    invisible(.Call(`_RaspberryPiR_testing_freeMemory`))
}

testingDHT <- function(pin = 0L) {
    .Call(`_RaspberryPiR_testingDHT`, pin)
}

testingPhotoRes <- function(pin = 7L) {
    .Call(`_RaspberryPiR_testingPhotoRes`, pin)
}

testingMQ2 <- function(pin = 0L, SPICLK = 14L, SPIMISO = 13L, SPIMOSI = 12L, SPICS = 10L, mq2_dpin = 25L, mq2_apin = 0L) {
    .Call(`_RaspberryPiR_testingMQ2`, pin, SPICLK, SPIMISO, SPIMOSI, SPICS, mq2_dpin, mq2_apin)
}

simpleCapture <- function(path = "/home/pi/Pictures/raspicam_image.ppm", width = 1L, height = 1L) {
    .Call(`_RaspberryPiR_simpleCapture`, path, width, height)
}

LL_wiringPiSetup <- function() {
    invisible(.Call(`_RaspberryPiR_LL_wiringPiSetup`))
}

LL_pinMode <- function(pin, mode) {
    invisible(.Call(`_RaspberryPiR_LL_pinMode`, pin, mode))
}

LL_digitalWrite <- function(pin, mode) {
    invisible(.Call(`_RaspberryPiR_LL_digitalWrite`, pin, mode))
}

LL_digitalRead <- function(pin) {
    .Call(`_RaspberryPiR_LL_digitalRead`, pin)
}

LL_pullUpDnControl <- function(pin, pud) {
    invisible(.Call(`_RaspberryPiR_LL_pullUpDnControl`, pin, pud))
}

LL_millis <- function() {
    .Call(`_RaspberryPiR_LL_millis`)
}

LL_micros <- function() {
    .Call(`_RaspberryPiR_LL_micros`)
}

